# Site settings
title: Rising Stars Consulting
email: your-email@domain.com
url: www.risingstarsconsulting.com
description: "Providing tailored education services for navigating and advocating for the best education experience for those with special needs"
keywords: "iep, individual education plan, special ed, special education, learning disability, disabilities, special needs,"
skills: "Helping You Navigate Special Needs Education"
meta_author: Sanders Mimi

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: AAC5E2 #80B3FF
  primary-rgb: "104,145,195" #"128,179,255" 
  secondary: 6891C3 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Rising Stars Consulting
  location: Nashville, TN
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title:
    url:
  - title:
    url:
  - title:
    url:
  - title:
    url:
  - title:
    url:

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Credits content
credits:

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
